services:
  db:
    container_name: db
    image: postgis/postgis:16-3.4-alpine
    restart: always
    environment:
      POSTGRES_DB: food-twin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/data
    command: >
      postgres -c shared_buffers=1GB
               -c work_mem=128MB
               -c maintenance_work_mem=1GB
               -c autovacuum=off
               -c synchronous_commit=off
               -c checkpoint_timeout=1h
               -c max_wal_size=10GB
               -c wal_compression=on
               -c effective_cache_size=2GB
               -c max_parallel_workers_per_gather=4
               -c max_worker_processes=8
               -c max_parallel_workers=8
               -c wal_buffers=16MB
               -c log_min_duration_statement=1000
               -c random_page_cost=1.1
               -c track_activity_query_size=2048
               -c shared_preload_libraries='pg_stat_statements'
