services:
  db:
    container_name: db
    image: postgis/postgis:16-3.4-alpine
    restart: always
    environment:
      POSTGRES_DB: food-twin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/data
